apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: efk-filebeat
  name: efk-filebeat-config
  namespace: efk
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata:
          in_cluster: true

    output.elasticsearch:
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
